### ISSUE TITLE
Strange garbage characters in PCI_DSS-field

### ISSUE THREAD

**Issue by MagnusMWW** [wazuh/ossec-wazuh#28] opened 2016-05-30 14:02 UTC
We have been running wazuh for a few weeks, mostly for the analysisd-functionality. We use logstash to consume a kafka topic, and send the desired logs to a file, which analysisd then looks over. Logstash then picks up the resulting alerts.json-file and sends forward into Elasticsearch. Over all we are very pleased with it. However, we have noticed a few interresting issues with the PCI_DSS-field recently though.

It seems that all events that have the group "pci_dss_11.4" gets one or more tailing garbage characters in the resulting PCI_DSS array element. This is an example:

> {"rule":{"level":6,"comment":"SSH insecure connection attempt (scan).","sidid":5706,"firedtimes":1,"groups":["syslog","sshd","recon"],"PCI_DSS":["11.4}"]},"srcip":"10.10.0.20","full_log":"May 30 15:12:09 aserver sshd[2360]: Did not receive identification string from 10.10.0.20","program_name":"sshd","decoder":{"parent":"sshd","name":"sshd"},"hostname":"aserver","timestamp":"2016 May 30 15:12:14","location":"/var/ossec/logs/logstash/logstash.log"}

This seems to be true for all alerts generated that has that group. From what I have seen it doesn't matter if it has more than one groups or just the 11.4 one. The same problem occurs either way.

The big issue with this for us, is that logstash sometimes barfs on the messages that contains this extra character in the alerts.json-file, resulting in some messages not being picked up. It can be mitigated by removing the group from the rules that we are interrested in, but it is not feasable in the long run of course, and will likely be wiped by future rule updates, etc etc.

Have anyone seen this before? We are running the latest release 1.1.1 from https://github.com/wazuh/ossec-wazuh/releases

**Comment by vikman90** [comment] 2016-05-30 16:24
Hi @MagnusMWW.

We tried to reproduce the issue but we haven't gotten it. We reviewed the code and found a bug, we fixed it but we are not sure that it solves this issue.

Could you give some more information, please? Is your example a direct output from alerts.json? Does this issue happen everytime that Logstash logs that message?

Thank you very much for your feedback!

**Comment by MagnusMWW** [comment] 2016-05-31 10:26
Hello @vikman90 !

Regarding more detailed information; yes, the example above is a line directly from the alerts.json-file. Logstash will sometimes pick up the messages that are affected, and sometimes not. Seems that the reason is that the garbage character is sometimes a # or ] that is actually parseable, and then it is picked up OK, but we get the character in the field, so the element will be "11.4]" or "11.4#" in Elasticsearch for example. The character seems to change between service restarts of analysisd.

We are running this on RHEL7, and wazuh was built on a Centos7/RHEL7-machine with current development tools.

Is the fix you mentioned this commit? 63c9342de0a2cb7e39f5f0306bca9c6d1a5cbd7a

If so, maybe we can do a test-build of that and see if the problem still persists or not. Will get back to you on that.

Thanks for the quick response!

**Comment by vikman90** [comment] 2016-05-31 12:26
Hello @MagnusMWW 

Yes, we did that fix and also this one: https://github.com/wazuh/ossec-wazuh/commit/7abeab89142e610a5ab4da7e38e4270e3dac21b5. We're reproducing the issue in our lab and testing the fix.

If you could test these changes on your machine, it would be great. In that case, please tell us your results.

Thank you very much again!

**Comment by MagnusMWW** [comment] 2016-05-31 16:01
No problem!

I did a quick check in test, and it seems to work with the latest revision. Will plan an upgrade of production, but i don't see any reason why it shouldn't work. Will update here afterwards nonetheless.

Thanks!

**Comment by vikman90** [comment] 2016-06-08 10:25
Hello @MagnusMWW.

Could you test those commits on your system? Did you found any issue? We tested them and found no problems. If you didn't find problems, we can close this issue.

Thank you!

**Comment by MagnusMWW** [comment] 2016-06-13 08:33
Hello again @vikman90 !

Sorry for the lack of updates. I have been abscent for a few days. I will do some more testing to confirm that this is working. Will get back here soon with the results.

**Comment by MagnusMWW** [comment] 2016-06-13 11:35
Back again!

We did a new test-build and deployed it in our production environment. So far everything looks good. I have yet only received one message where the problem used to occur (SSHD brute force rule, sid 5712), but that looks good.

Before test build:
> {"rule":{"level":10,"comment":"SSHD brute force trying to get access to the system.","sidid":5712,"frequency":6,"firedtimes":1,"groups":["syslog","sshd","authentication_failures"],"PCI_DSS":["11.4º","10.2.4","10.2.5"]},"srcip":"10.10.0.20","srcuser":"test","full_log":"Jun 13 13:03:55 aserver sshd[23558]: Failed password for invalid user test from 10.10.0.20 port 55843 ssh2","program_name":"sshd","decoder":{"parent":"sshd","name":"sshd"},"hostname":"aserver","timestamp":"2016 Jun 13 13:03:55","location":"/var/ossec/logs/logstash/logstash.log"}

After test build:
> {"rule":{"level":10,"comment":"SSHD brute force trying to get access to the system.","sidid":5712,"frequency":6,"firedtimes":1,"groups":["syslog","sshd","authentication_failures"],"PCI_DSS":["11.4","10.2.4","10.2.5"]},"srcip":"10.10.0.20","srcuser":"test","full_log":"Jun 13 13:25:57 aserver sshd[23848]: Invalid user test from 10.10.0.20","program_name":"sshd","decoder":{"parent":"sshd","name":"sshd"},"hostname":"aserver","timestamp":"2016 Jun 13 13:26:00","location":"/var/ossec/logs/logstash/logstash.log"}

I think we can conclude that the issue is resolved. Thank you for the quick fix and response. It is much appreciated!

**Comment by vikman90** [comment] 2016-06-13 11:43
Hi @MagnusMWW!

I'm glad that the issue is solved. Thank you very much for your feedback and for your testing! It has been very helpful to us.

Best regards!

**Closed by vikman90** 2016-06-13 11:43 UTC
